#!/bin/sh
set -ev

if [ -z "$MARATHON_APP_ID" ]; then
  echo "Not running in marathon, so I will not compile the config template."
  echo "To force config template compilation, set \$MARATHON_APP_ID."
else
  echo "Compiling config template - ${SERVER_CONFIG}.j2"
  /bin/env_parse ${SERVER_CONFIG}.j2
fi

su socrata -c '/usr/bin/java \
    -Dconfig.file=${SERVER_CONFIG} \
    -jar $SERVER_ARTIFACT \
    com.socrata.datacoordinator.primary.MigrateSchema migrate \
    '

exec su socrata -c '/usr/bin/java \
    -Xmx${JAVA_XMX} \
    -Xms${JAVA_XMX} \
    -Dconfig.file=${SERVER_CONFIG} \
    -Djava.net.preferIPv4Stack=true \
    -Dcom.sun.management.jmxremote.port=${JMX_PORT} \
    -Dcom.sun.management.jmxremote.rmi.port=${JMX_PORT} \
    -Dcom.sun.management.jmxremote.ssl=false \
    -Dcom.sun.management.jmxremote.authenticate=false \
    -Djava.rmi.server.hostname=${ARK_HOST:-localhost} \
    -XX:MaxMetaspaceSize=${JAVA_MAX_METASPACE} \
    -jar $SERVER_ARTIFACT \
    com.socrata.datacoordinator.service.Main \
    '
