#!/bin/bash
set -ev
set -o pipefail

if [ -d /mnt/mesos/sandbox ]; then
    export HEAPDUMP="-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/mnt/mesos/sandbox"
    # the sandbox is owned by root and not accessible by socrata, so
    # make it thus accessible...
    chmod o+wrx /mnt/mesos/sandbox
else
    export HEAPDUMP=""
fi

if [ -n "$ECS_CONTAINER_METADATA_URI_V4" ]; then
    ARK_HOST="$(curl -sf "$ECS_CONTAINER_METADATA_URI_V4" | jq -r '.Networks[0].IPv4Addresses[0]')"
    export ARK_HOST
fi

if [ -z "$MARATHON_APP_ID" ] && [ -z "$ECS_CONTAINER_METADATA_URI_V4" ]; then
  echo "Not running in marathon, so I will not compile the config template."
  echo "To force config template compilation, set \$MARATHON_APP_ID."
else
  echo "Compiling config template - ${SERVER_CONFIG}.j2"
  /bin/env_parse ${SERVER_CONFIG}.j2
fi

su socrata -c '/usr/bin/java \
    -Dconfig.file=${SERVER_CONFIG} \
    -jar $SERVER_ARTIFACT \
    com.socrata.datacoordinator.primary.MigrateSchema migrate \
    '

exec su socrata -c 'exec /usr/bin/java \
    -Xmx${JAVA_XMX} \
    -Xms${JAVA_XMX} \
    -Dconfig.file=${SERVER_CONFIG} \
    -Djava.net.preferIPv4Stack=true \
    -Dcom.sun.management.jmxremote.port=${JMX_PORT} \
    -Dcom.sun.management.jmxremote.rmi.port=${JMX_PORT} \
    -Dcom.sun.management.jmxremote.ssl=false \
    -Dcom.sun.management.jmxremote.authenticate=false \
    -Djava.rmi.server.hostname=${ARK_HOST:-localhost} \
    -XX:MaxMetaspaceSize=${JAVA_MAX_METASPACE} \
    ${HEAPDUMP} \
    -jar $SERVER_ARTIFACT \
    com.socrata.datacoordinator.service.Main \
    '
