apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: data-coordinator
  description: |
    The data-coordinator service takes data upserts, inserts them to the truth
    store, watches truth store logs, and writes the data to postgres tables (in
    truth) that function as the secondary store event queues. These queues are
    monitored by secondary-watchers, which then write that data to their
    associated data store.
  links:
    - title: "OpsDoc"
      url: "https://socrata.atlassian.net/wiki/spaces/ONCALL/pages/2158657785/OpsDoc+-+delta-importer-2"
    - title: "Teams Channel"
      url: "https://teams.microsoft.com/l/channel/19%3Acc7bc69e4e1349c98d6de53dea8fcd97%40thread.tacv2/egress-q-and-a?groupId=102da3ef-c928-4a59-afe5-f0d51e6443dd&tenantId=7cc5f0f9-ee5b-4106-a62d-1b9f7be46118"
  annotations:
    github.com/project-slug: socrata-platform/data-coordinator
    backstage.io/techdocs-ref: dir:.
  tags:
    - scala
spec:
  type: service
  owner: egress
  lifecycle: production
